// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD64rpGZ5QJ-hVFX94EIwbGPsUwmA6WN2E',
    appId: '1:333292401413:web:3f1a063fdf6d06afe5bd6c',
    messagingSenderId: '333292401413',
    projectId: 'tracker-aa86b',
    authDomain: 'tracker-aa86b.firebaseapp.com',
    storageBucket: 'tracker-aa86b.firebasestorage.app',
    measurementId: 'G-GF7J2Q54JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRl_x79rY0AIiWod-CsPwnWnUuNrYptZU',
    appId: '1:333292401413:android:7dbe0bb9e81d71d1e5bd6c',
    messagingSenderId: '333292401413',
    projectId: 'tracker-aa86b',
    storageBucket: 'tracker-aa86b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfFuZsUnPLyLUj18XgDAohduqXVPGPaKg',
    appId: '1:333292401413:ios:2dcefd1074fbb131e5bd6c',
    messagingSenderId: '333292401413',
    projectId: 'tracker-aa86b',
    storageBucket: 'tracker-aa86b.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfFuZsUnPLyLUj18XgDAohduqXVPGPaKg',
    appId: '1:333292401413:ios:2dcefd1074fbb131e5bd6c',
    messagingSenderId: '333292401413',
    projectId: 'tracker-aa86b',
    storageBucket: 'tracker-aa86b.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );
}
